import { mutationDiff, validDiff, type Diff } from "./full-core";

// Structural diffs only. Never read node content, form values or attribute values.
// Ignore the private subtree and chrome generated by our own session controls.
export function observeMutations(root: HTMLElement, onDiff: (diff: Diff) => void): () => void {
  const observer = new MutationObserver((records) => {
    for (const record of records.slice(0, 100)) {
      const el = record.target.nodeType === Node.ELEMENT_NODE ? record.target as Element : record.target.parentElement;
      if (el?.closest('input, textarea, select, [contenteditable], [data-dvr-private], [data-testid^="dvr-"], script, style')) continue;
      const diff = mutationDiff(record, root);
      if (diff && validDiff(diff)) onDiff(diff);
    }
  });
  observer.observe(root, { subtree: true, childList: true, attributes: true, characterData: true });
  return () => observer.disconnect();
}
