// [F42 §3 / §5] jsdom gate for the v1 top-bar "Preview v2 UI" link: the href
// must be GENERATED by URLSearchParams, so an already-queried dashboard URL
// ('/?key=<token>') yields '&ui=v2' - never a second '?' ('?ui=v2'), which is
// exactly what made the live ticket link render v1. Runs in the vitest jsdom
// environment (after pnpm install), unlike the dependency-free node tests.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

const ui = readFileSync("payloads/ui.html", "utf8").replace(/\r\n?/g, "\n");

// Load the SHIPPED builder out of payloads/ui.html (single source of truth).
const builderSrc = ui.match(/function v2PreviewHref\(base\)\{[^\n]*\}/)?.[0];
expect(builderSrc, "v2PreviewHref not found in payloads/ui.html").toBeTruthy();

// eslint-disable-next-line @typescript-eslint/no-implied-eval
const v2PreviewHref = new Function(`${builderSrc}\nreturn v2PreviewHref;`)() as (base?: string) => string;

describe("F42 v1 -> v2 preview link href", () => {
  it("inserts '&ui=v2' (never '?ui=v2') when the dashboard URL already has a query", () => {
    const hrefs = [
      v2PreviewHref("http://127.0.0.1:7331/?key=tok123"),
      v2PreviewHref("http://127.0.0.1:7331/index.html?key=tok123&mirror=1"),
    ];
    for (const href of hrefs) {
      expect(href).not.toContain("?ui=");
      expect(href).toContain("&ui=v2");
    }
    const u = new URL(hrefs[0]);
    expect(u.searchParams.get("key")).toBe("tok123");
    expect(u.searchParams.get("ui")).toBe("v2");
  });

  it("uses '?ui=v2' only when the URL carries no query at all", () => {
    const href = v2PreviewHref("http://127.0.0.1:7331/");
    expect(href).toBe("http://127.0.0.1:7331/?ui=v2");
  });

  it("normalises the exact live bug shape and keeps the key clean", () => {
    // the operator's live URL shape: key token followed by a SECOND '?'
    const href = v2PreviewHref("http://127.0.0.1:7331/?key=tok123?ui=v2");
    const u = new URL(href);
    expect(u.searchParams.get("ui")).toBe("v2");
    expect(u.searchParams.get("key")).toBe("tok123");
    expect(href).not.toContain("?ui=");
    expect(href).toContain("&ui=v2");
  });

  it("the v1 top bar wires the link through the builder", () => {
    expect(ui).toContain('id="v2PreviewLink"');
    expect(ui).toContain("a.setAttribute('href',v2PreviewHref())");
    expect(ui).toContain("u.searchParams.set('ui','v2')");
  });
});
