// [F56-c] Additive F56 UI-id lock. F56_SEARCH_IDS is the Plan §I inventory
// verbatim (71 entries). Ids render as DOM ids under the f56.search.* namespace,
// which cannot collide with the frozen 219 (asserted by
// src/tests/smoke/f56-f57-ids.test.ts). The 219 registry is one-directional
// and stays byte-identical - nothing here is merged into
// src/lib/regression-ids.ts. Template ids render as deterministic runtime
// children (`<template>.<stable suffix>`), never derived from a title or URL.

export const F56_SEARCH_IDS = [
  "f56.search.nav",
  "f56.search.view",
  "f56.search.commandBar",
  "f56.search.paletteCommand",
  "f56.search.query",
  "f56.search.queryDescription",
  "f56.search.queryClear",
  "f56.search.querySubmit",
  "f56.search.urlImport",
  "f56.search.urlImportValidation",
  "f56.search.scope",
  "f56.search.keyboardHelp",
  "f56.search.filters",
  "f56.search.filtersReset",
  "f56.search.categoryGroup",
  "f56.search.categoryChip",
  "f56.search.licenceGroup",
  "f56.search.licenceChip",
  "f56.search.sizeSlider",
  "f56.search.sizeValue",
  "f56.search.sortSelector",
  "f56.search.sortOption",
  "f56.search.statusLive",
  "f56.search.adapterStatusList",
  "f56.search.adapterStatusRow",
  "f56.search.cancelSearch",
  "f56.search.results",
  "f56.search.resultsHeader",
  "f56.search.resultsLoading",
  "f56.search.resultsEmpty",
  "f56.search.resultsError",
  "f56.search.resultsRateLimited",
  "f56.search.resultRow",
  "f56.search.resultSelection",
  "f56.search.resultSourceBadge",
  "f56.search.resultCategoryGlyph",
  "f56.search.resultTitle",
  "f56.search.resultCreator",
  "f56.search.resultSize",
  "f56.search.resultDate",
  "f56.search.resultLicence",
  "f56.search.resultActions",
  "f56.search.resultFetch",
  "f56.search.resultPreview",
  "f56.search.resultPurchase",
  "f56.search.resultRetry",
  "f56.search.previewDialog",
  "f56.search.purchaseNotice",
  "f56.search.progressRail",
  "f56.search.progressHeader",
  "f56.search.progressList",
  "f56.search.progressEmpty",
  "f56.search.progressRow",
  "f56.search.progressTransport",
  "f56.search.progressGid",
  "f56.search.progressQbittorrentHandle",
  "f56.search.progressStage",
  "f56.search.progressSparkline",
  "f56.search.progressSpeed",
  "f56.search.progressEta",
  "f56.search.progressRetry",
  "f56.search.progressCancel",
  "f56.search.progressLive",
  "f56.search.postFetchPipeline",
  "f56.search.torrentLane",
  "f56.search.mirrorOff",
  "f56.search.ownStorageResults",
  "f56.search.filterSelectionCount",
  "f56.search.classifierBlock",
  "f56.search.contentLengthFailure",
  "f56.search.snapshotFailure",
] as const;

/** Plan §I: stable templates. Runtime children use deterministic suffixes -
 *  chips/sort options suffix with their enum value; row/cell ids suffix with
 *  `<adapterId>.<resultId>`; progress cells suffix with `<fetchId>`. */
export const F56_SEARCH_TEMPLATES = [
  "f56.search.categoryChip",
  "f56.search.licenceChip",
  "f56.search.sortOption",
  "f56.search.adapterStatusRow",
  "f56.search.resultRow",
  "f56.search.resultSelection",
  "f56.search.resultSourceBadge",
  "f56.search.resultCategoryGlyph",
  "f56.search.resultTitle",
  "f56.search.resultCreator",
  "f56.search.resultSize",
  "f56.search.resultDate",
  "f56.search.resultLicence",
  "f56.search.resultActions",
  "f56.search.resultFetch",
  "f56.search.resultPreview",
  "f56.search.resultPurchase",
  "f56.search.resultRetry",
  "f56.search.progressRow",
  "f56.search.progressTransport",
  "f56.search.progressGid",
  "f56.search.progressQbittorrentHandle",
  "f56.search.progressStage",
  "f56.search.progressSparkline",
  "f56.search.progressSpeed",
  "f56.search.progressEta",
  "f56.search.progressRetry",
  "f56.search.progressCancel",
] as const;

/** Single-instance ids: rendered literally exactly once when present. */
export const F56_SEARCH_STATIC = F56_SEARCH_IDS.filter(
  (id) => !(F56_SEARCH_TEMPLATES as readonly string[]).includes(id)
);

export type F56SearchId = (typeof F56_SEARCH_IDS)[number];
